name: Android app Kotlin linter
on:
    # Run linter whenever a Kotlin file changes
    pull_request:
        paths:
            - .github/workflows/android-ktlint.yml
            - android/**/*.kt
    # Run linter if requested manually from the Actions tab
    workflow_dispatch:
jobs:
    ktlint:
        runs-on: ubuntu-latest
        steps:
            # Checkout repository
            - uses: actions/checkout@v2

            # Install Ktlint
            - uses: nbadal/action-ktlint-setup@v1
              with:
                  ktlint_version: 0.40.0

            # Check formatting
            - run: |
                cd android
                ktlint -a
